## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0

notifications:
  email: false

after_success:
  - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: deploy docs
      language: julia
      os: linux
      julia: 1.0
      script:
        - julia -e 'import Pkg; Pkg.instantiate(); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
      after_success: skip
    - stage: Semantic Release
      if: branch = master AND type != pull_request
      language: python
      os: linux
      python: 3.6
      install:
        - pip install typing
        - pip install python-semantic-release
      script:
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - semantic-release publish
      after_success: skip
