site_name:        DeIdentification.jl
site_author:      Paul Stey
repo_url:         https://github.com/bcbi/deidentification.jl
site_description: A Julia package for de-identifying data

site_url: https://bcbi.github.io/ #this is the main site!

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: bcbi_logo.svg

extra_css:
  - styles/dark_mode.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
  - footnotes

nav:
  - Home: 'index.md'
  - Functions: 'documentation.md'
